[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    X-Frame-Options = "ALLOWALL"

<iframe 
  src="https://your-netlify-site.netlify.app" 
  style="border: none; width: 100%; height: 600px;">
</iframe>
